package Vista;

import Controlador.Controlador;
import static Modelo.Producto.TIPOS;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Universidad Estatal a Distancia (UNED)
 * Cuatrimestre: I Cuatrimestre 2026
 * Proyecto: Proyecto Evaluativo - Estructura de Datos
 * Descripción: Formulario de Gestion De Productos de Reposteria
 * Estudiante: Jose David Canizales Azocar
 * Fecha: Marzo 2026
 */
public class GestionProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionProductos
     */
   
    private final Controlador controlador;
    
    public GestionProductos(Controlador controlador) {
        this.controlador = controlador;
        initComponents();
        cargarProductosEnTabla();
        cargarConteosEnTabla();
        // Cargar tipos en combobox
        cargarTipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();
        contenedorTablaProductos = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        contenedorTablaConteo = new javax.swing.JScrollPane();
        tablaConteo = new javax.swing.JTable();
        tituloVentana1 = new javax.swing.JLabel();
        tituloTablaDepartamento = new javax.swing.JLabel();
        tituloTablaConteo = new javax.swing.JLabel();

        setTitle("Gestion de Productos");

        lblNombre.setText("Nombre");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        lblPrecio.setText("Precio");

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        contenedorTablaProductos.setViewportView(tablaProductos);

        tablaConteo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConteo.getTableHeader().setReorderingAllowed(false);
        tablaConteo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConteoMouseClicked(evt);
            }
        });
        contenedorTablaConteo.setViewportView(tablaConteo);
        if (tablaConteo.getColumnModel().getColumnCount() > 0) {
            tablaConteo.getColumnModel().getColumn(0).setResizable(false);
            tablaConteo.getColumnModel().getColumn(1).setResizable(false);
        }

        tituloVentana1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana1.setText("Gestion de Productos");
        tituloVentana1.setToolTipText("");

        tituloTablaDepartamento.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloTablaDepartamento.setText("Listado de Productos");
        tituloTablaDepartamento.setToolTipText("");

        tituloTablaConteo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloTablaConteo.setText("Conteo de Productos");
        tituloTablaConteo.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrecio)
                                .addGap(115, 115, 115)
                                .addComponent(lblTipo)
                                .addGap(135, 135, 135))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipo, 0, 191, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(contenedorTablaConteo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloTablaDepartamento)
                                .addGap(75, 75, 75)
                                .addComponent(tituloVentana1))
                            .addComponent(tituloTablaConteo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(contenedorTablaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloVentana1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tituloTablaDepartamento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(tituloTablaConteo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTablaConteo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(lblTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(contenedorTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarFormulario();
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        capturarDatosFormulario();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void tablaConteoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConteoMouseClicked

    }//GEN-LAST:event_tablaConteoMouseClicked

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaProductosMouseClicked
    
    // ================ Metodos Varios ================
    
    // Cargar tipos en el combobox
    private void cargarTipos() {
        tipo.setModel(
            new javax.swing.DefaultComboBoxModel<>(
            TIPOS
        ));
    } 
    
    
    // ================ Metodos de Registro ================
    
        // Limpia todos los campos del formulario dejandolos en su estado inicial.
    private void limpiarFormulario() {
        this.nombre.setText("");
        this.tipo.setSelectedIndex(0);
        this.precio.setText("");
    }
    
    // Valida que los campos del formulario no esten vacios antes de registrar.
    private void validarCampos() {
        String nombre = this.nombre.getText().trim();
        String tipo = (String) this.tipo.getSelectedItem();
        String precio = this.precio.getText().trim();
        if (nombre.isEmpty()) {
            throw new IllegalArgumentException("El campo nombre es obligatorio");
        }
        if (tipo == null  ) {
            throw new IllegalArgumentException("Debe seleccionar una tipo de reposteriaa");
        }
        if (precio.isEmpty()) {
            throw new IllegalArgumentException("El campo precio es obligatorio");
        }
    }
        
    /**
     * Captura los datos del formulario, valida su formato e intenta
     * registrar el articulo.
    */
    private void capturarDatosFormulario() {
        try {
            validarCampos();
            String nombre = this.nombre.getText().trim();
            Double precio  = Double.parseDouble(this.precio.getText().trim());
            String tipo = (String) this.tipo.getSelectedItem();
            controlador.agregarProducto(
                nombre,
                precio,
                tipo
            );
            limpiarFormulario();
            cargarProductosEnTabla();  // Refrescar la tabla
            cargarConteosEnTabla(); // Refrescar la tabla
        } catch (IllegalArgumentException e) {
            // Error de validación - mensaje específico
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Error de Validacion", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
             // Error inesperado
             JOptionPane.showMessageDialog(this, 
                 "Error inesperado: " + e.getMessage(), 
                 "Error", 
                 JOptionPane.ERROR_MESSAGE);
         }
    }
    
    // ================ Metodos de Listado ================
    
    /**
    * Carga y muestra todos los registros.
    */
    private void cargarProductosEnTabla() {
        try {
            mostrarRegistrosEnTabla(controlador.obtenerProductosArray());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Muestra el listado de celebraciones de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTabla(Object[][] datos) {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0); // Limpiar tabla
        
       
        boolean hayRegistros = false;
        
        // Recorrer array de datos
        for (Object[] fila : datos) {
            hayRegistros = true;
            // Agregar fila: ID, Nombre, Precio, Tipo
            modelo.addRow(new Object[] {
                fila[0],  // ID
                fila[1],  // Nombre
                fila[2],  // Precio
                fila[3]   // Tipo
            });
        }
        // Desplegar fila en caso de no tener registros
        if (!hayRegistros) {
            modelo.addRow(new Object[] { "No hay productos registrados", "", "", "" });
        }
    }
    
    /**
    * Carga y muestra los conteos.
    */
    private void cargarConteosEnTabla() {
        try {
            mostrarConteosEnTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }  
    
    /**
     * Muestra el listado de conteos de forma tabular.
     *
    */
    private void mostrarConteosEnTabla() {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaConteo.getModel();
        
        // Cargar datos en 0 primero
        modelo.setValueAt("Dulce", 0, 0);
        modelo.setValueAt(0, 0, 1);
        modelo.setValueAt("Salada", 1, 0);
        modelo.setValueAt(0, 1, 1);
        
        // Cargar datos reales
        int dulce = controlador.contarTipo("Dulce");
        int salada = controlador.contarTipo("Salada");
    
        modelo.setValueAt(dulce, 0, 1);
        modelo.setValueAt(salada, 1, 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JScrollPane contenedorTablaConteo;
    private javax.swing.JScrollPane contenedorTablaProductos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JTable tablaConteo;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JLabel tituloTablaConteo;
    private javax.swing.JLabel tituloTablaDepartamento;
    private javax.swing.JLabel tituloVentana1;
    // End of variables declaration//GEN-END:variables
}
