package Vista;

import Controlador.Controlador;
import static Modelo.Producto.TIPOS;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Universidad Estatal a Distancia (UNED)
 * Cuatrimestre: I Cuatrimestre 2026
 * Proyecto: Proyecto Evaluativo - Estructura de Datos
 * Descripción: Formulario de Gestion De Productos de Reposteria
 * Estudiante: Jose David Canizales Azocar
 * Fecha: Marzo 2026
 */
public class GestionProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionProductos
     */
   
    private final Controlador controlador;
    
    public GestionProductos(Controlador controlador) {
        this.controlador = controlador;
        initComponents();
        cargarProductosEnTabla();
        // Cargar tipos en combobox
        cargarTipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();
        tituloVentana = new javax.swing.JLabel();
        contenedorTablaDepartamento = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();

        setTitle("Gestion de Productos");

        lblNombre.setText("Nombre");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        lblPrecio.setText("Precio");

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        tituloVentana.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana.setText("Gestion de Productos");
        tituloVentana.setToolTipText("");

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaContenido.getTableHeader().setReorderingAllowed(false);
        tablaContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaContenidoMouseClicked(evt);
            }
        });
        contenedorTablaDepartamento.setViewportView(tablaContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrecio)
                                        .addGap(115, 115, 115)
                                        .addComponent(lblTipo)
                                        .addGap(135, 135, 135))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipo, 0, 206, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(tituloVentana)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contenedorTablaDepartamento)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTablaDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(lblTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarFormulario();
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        capturarDatosFormulario();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void tablaContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaContenidoMouseClicked

    }//GEN-LAST:event_tablaContenidoMouseClicked
    
    // ================ Metodos Varios ================
    
    // Cargar tipos en el combobox
    private void cargarTipos() {
        tipo.setModel(
            new javax.swing.DefaultComboBoxModel<>(
            TIPOS
        ));
    } 
    
    
    // ================ Metodos de Registro ================
    
        // Limpia todos los campos del formulario dejandolos en su estado inicial.
    private void limpiarFormulario() {
        this.nombre.setText("");
        this.tipo.setSelectedIndex(0);
        this.precio.setText("");
    }
    
    // Valida que los campos del formulario no esten vacios antes de registrar.
    private void validarCampos() {
        String nombre = this.nombre.getText().trim();
        String tipo = (String) this.tipo.getSelectedItem();
        String precio = this.precio.getText().trim();
        if (nombre.isEmpty()) {
            throw new IllegalArgumentException("El campo nombre es obligatorio");
        }
        if (tipo == null  ) {
            throw new IllegalArgumentException("Debe seleccionar una tipo de reposteriaa");
        }
        if (precio.isEmpty()) {
            throw new IllegalArgumentException("El campo precio es obligatorio");
        }
    }
        
    /**
     * Captura los datos del formulario, valida su formato e intenta
     * registrar el articulo.
    */
    private void capturarDatosFormulario() {
        try {
            validarCampos();
            String nombre = this.nombre.getText().trim();
            Double precio  = Double.parseDouble(this.precio.getText().trim());
            String tipo = (String) this.tipo.getSelectedItem();
            controlador.agregarProducto(
                nombre,
                precio,
                tipo
            );
            limpiarFormulario();
            cargarProductosEnTabla();  // Refrescar la tabla
        } catch (IllegalArgumentException e) {
            // Error de validación - mensaje específico
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Error de Validacion", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
             // Error inesperado
             JOptionPane.showMessageDialog(this, 
                 "Error inesperado: " + e.getMessage(), 
                 "Error", 
                 JOptionPane.ERROR_MESSAGE);
         }
    }
    
    // ================ Metodos de Listado ================
    
    /**
    * Carga y muestra todos los registros.
    */
    private void cargarProductosEnTabla() {
        try {
            mostrarRegistrosEnTabla(controlador.obtenerProductosArray());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    /**
     * Muestra el listado de celebraciones de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTabla(Object[][] datos) {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaContenido.getModel();
        modelo.setRowCount(0); // Limpiar tabla
        
       
        boolean hayRegistros = false;
        
        // Recorrer array de datos
        for (Object[] fila : datos) {
            hayRegistros = true;
            // Agregar fila: ID, Nombre, Cantidad, Precio
            modelo.addRow(new Object[] {
                fila[0],  // ID
                fila[1],  // Nombre
                fila[3],  // Cantidad
                fila[2]   // Precio
            });
        }
        // Desplegar fila en caso de no tener registros
        if (!hayRegistros) {
            modelo.addRow(new Object[] { "No hay productos registrados", "", "", "" });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JScrollPane contenedorTablaDepartamento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JTable tablaContenido;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
