package Vista;

import Controlador.Controlador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Universidad Estatal a Distancia (UNED)
 * Cuatrimestre: I Cuatrimestre 2026
 * Proyecto: Proyecto Evaluativo - Estructura de Datos
 * Descripción: Formulario de listado de productos
 * Estudiante: Jose David Canizales Azocar
 * Fecha: Marzo 2026
 */
public class Listar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar
     */
    
    private final Controlador controlador;
    
    public Listar(Controlador controlador) {
        this.controlador = controlador;
        initComponents(); 
        cargarProductosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVentana = new javax.swing.JLabel();
        contenedorTablaDepartamento = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();
        botonRefrescarTabla = new javax.swing.JButton();

        setClosable(true);
        setTitle("Listar Productos");

        tituloVentana.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana.setText("Listar Productos");
        tituloVentana.setToolTipText("");

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaContenido.getTableHeader().setReorderingAllowed(false);
        tablaContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaContenidoMouseClicked(evt);
            }
        });
        contenedorTablaDepartamento.setViewportView(tablaContenido);

        botonRefrescarTabla.setText("Refrescar Tabla");
        botonRefrescarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloVentana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRefrescarTabla))
                    .addComponent(contenedorTablaDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRefrescarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloVentana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTablaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaContenidoMouseClicked

    }//GEN-LAST:event_tablaContenidoMouseClicked

    private void botonRefrescarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarTablaActionPerformed
        cargarProductosEnTabla();
    }//GEN-LAST:event_botonRefrescarTablaActionPerformed

    /**
     * Carga y muestra todos los registros.
     */
    private void cargarProductosEnTabla() {
        try {
            mostrarRegistrosEnTabla(controlador.obtenerProductosArray());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    /**
     * Muestra el listado de celebraciones de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTabla(Object[][] datos) {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaContenido.getModel();
        modelo.setRowCount(0); // Limpiar tabla
        
       
        boolean hayRegistros = false;
        
        // Recorrer array de datos
        for (Object[] fila : datos) {
            hayRegistros = true;
            // Agregar fila: ID, Nombre, Cantidad, Precio
            modelo.addRow(new Object[] {
                fila[0],  // ID
                fila[1],  // Nombre
                fila[3],  // Cantidad
                fila[2]   // Precio
            });
        }
        // Desplegar fila en caso de no tener registros
        if (!hayRegistros) {
            modelo.addRow(new Object[] { "No hay productos registrados", "", "", "" });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRefrescarTabla;
    private javax.swing.JScrollPane contenedorTablaDepartamento;
    private javax.swing.JTable tablaContenido;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
